config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  get '/about', to: 'pages#about'
  get '/work', to: 'pages#work'
  get '/contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def work
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sa16Act2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<nav>
    <%= link_to "Home", root_path %>
    <%= link_to "About", about_path %>
    <%= link_to "Work", work_path %>
    <%= link_to "Contact", contact_path %>
</nav>
<h1>About</h1>
<p>My name is Kylan Plunk, I'm a back-end developer based in Ontario</p>
<p>I have a passion for creating functional and user-friendly websites that provide a seamless browsing experience.</p>
<p>With over 5 years of experience in the industry, I have worked with various clients and projects, ranging from small businesses to large corporations.</p>
<p>I hold a degree in Computer Science from the University of Memphis, where I gained a solid foundation in programming and software development.</p>

app/views/pages/contact.html.erb
<nav>

    <%= link_to "Home", root_path %>
    <%= link_to "About", about_path %>
    <%= link_to "Work", work_path %>
    <%= link_to "Contact", contact_path %>
</nav>

<h1>Contact Me</h1>
<div class="social-media-links">
    <a href="https://www.facebook.com/fakeprofile" target="_blank">
        <i class="fab fa-facebook"></i>
    </a>
    <a href="https://www.twitter.com/fakeprofile" target="_blank">
        <i class="fab fa-twitter"></i>
    </a>
    <a href="https://www.instagram.com/fakeprofile" target="_blank">
        <i class="fab fa-instagram"></i>
    </a>
</div>

<form>
    <label for="name">Name:</label>
    <input type="text" id="name" name="name" required>

    <label for="email">Email:</label>
    <input type="email" id="email" name="email" required>

    <label for="message">Message:</label>
    <textarea id="message" name="message" required></textarea>

    <button type="submit">Submit</button>
</form>

<style>
    form {
        display: flex;
        flex-direction: column;
        max-width: 20%;
        margin: auto
    }

    form input {
        margin-bottom: 10px;
    }
</style>

app/views/pages/home.html.erb
<nav>

    <%= link_to "Home", root_path %>
    <%= link_to "About", about_path %>
    <%= link_to "Work", work_path %>
    <%= link_to "Contact", contact_path %>
</nav>
<h1>Welcome</h1>
<p>Kylan Plunk | back-end developer</p>

app/views/pages/work.html.erb
<nav>
    <%= link_to "Home", root_path %>
    <%= link_to "About", about_path %>
    <%= link_to "Work", work_path %>
    <%= link_to "Contact", contact_path %>
</nav>
<h1>Portfolio</h1>
<div class="projects">
    <% 3.times do %>
        <div class="project">
            <img src="https://via.placeholder.com/300" alt="Project Image">
            <h3>Project Title</h3>
            <p>Project Description</p>
        </div>
    <% end %>
</div>

<style>
    .projects {
        display: flex;
        justify-content: space-around;

    }

    .project {
        padding: 5px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

</style>